# ====================================== Setup - Change here ======================================
# Everything in seconds
CLICKSTORM_DURATION = (10, 42)
POWERSURGE_DURATION = (6, 40)
LUCKY_STRIKES_DURATION = (9, 24)
METAL_DETECTOR_DURATION = (6, 40)
GOLDEN_CLICKS_DURATION = (15, 19)
SUPER_CLICKS_DURATION = (6, 40)

TINY_COOLDOWN = (2, 33)  # ClickStorm, Powersurge
SMALL_COOLDOWN = (7, 40)  # LuckyStrikes, MetalDetector
MEDIUM_COOLDOWN = (15, 21)  # Goldenclicks, Superclicks, Energize, Reload
BIG_COOLDOWN = (2, 2, 55)  # Darkritual

FARM_PERIOD_VALUE = 10

BOSS_FIGHT_FAILS_LIMIT = 3
BOSS_FIGHT_FAIL_INTERVAL = 150  # Based on Chronos, if farm in enabled inside this time range it's considered a fail

NUMBER_OF_AUTO_CLICKERS = 4
# =================================================================================================
CLICKSTORM_DURATION = CLICKSTORM_DURATION[0] * 60 + CLICKSTORM_DURATION[1]
POWERSURGE_DURATION = POWERSURGE_DURATION[0] * 60 + POWERSURGE_DURATION[1]
LUCKY_STRIKES_DURATION = LUCKY_STRIKES_DURATION[0] * 60 + LUCKY_STRIKES_DURATION[1]
METAL_DETECTOR_DURATION = METAL_DETECTOR_DURATION[0] * 60 + METAL_DETECTOR_DURATION[1]
GOLDEN_CLICKS_DURATION = GOLDEN_CLICKS_DURATION[0] * 60 + GOLDEN_CLICKS_DURATION[1]
SUPER_CLICKS_DURATION = SUPER_CLICKS_DURATION[0] * 60 + SUPER_CLICKS_DURATION[1]

TINY_COOLDOWN = TINY_COOLDOWN[0] * 60 + TINY_COOLDOWN[1]
SMALL_COOLDOWN = SMALL_COOLDOWN[0] * 60 + SMALL_COOLDOWN[1]
MEDIUM_COOLDOWN = MEDIUM_COOLDOWN[0] * 60 + MEDIUM_COOLDOWN[1]
BIG_COOLDOWN = BIG_COOLDOWN[0] * 3600 + BIG_COOLDOWN[1] * 60 + BIG_COOLDOWN[2]

GOLD_PICKUP_POS = [1300, 1400, 1500, 700]
GOLD_PICKUP_INTERVAL = 300

POWERS_POS = [1025, 300, 380, 460, 540, 620, 700, 780, 860, 940]
FARM_MODE_POS = (1809, 337)
ASCENSION_POS = (1809, 413)
ASCENSION_YES_BUTTON_POS = (840, 775)


HERO_TREEBEAST_POS = (220, 500)


GILD_NEW_POS = (1780, 866)
GILD_NEW_OPEN = (950, 550)
GILD_NEW_OPENALL_POS = (1425, 835)

GILD_INITIAL_POS = (275, 515)
GILD_CLOSE_POS = (1766, 63)

MAXIMUM_SCROLL_DOWN_GILD_POS = (1720, 730)
GILD_TREEBEAST_POS = (390, 210)

# After scrolldown
GILD_TSUCHI_POS = (1450, 330)
GILD_SKOGUR = (390, 430)

POWERS = None
DC = None
FARM_MODE = None
FARM_PERIOD_MARK = None
FARMS_INTERVAL_MARK = None
BOSS_FIGHT_FAILS = None
